# Generated by Django 4.2.2 on 2024-01-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malayalam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='Malayalam')),
            ],
        ),
    ]
