# Generated by Django 4.2.2 on 2024-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malayalam',
            name='image',
            field=models.ImageField(default='', upload_to='img/%y'),
        ),
    ]
