# Generated by Django 4.2.2 on 2024-02-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_malayalam_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=250)),
                ('e_director', models.CharField(max_length=250)),
                ('e_year', models.DateField()),
                ('e_image', models.ImageField(default='', upload_to='img/%y')),
            ],
        ),
    ]
