# Generated by Django 4.2.2 on 2024-02-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english',
            name='e_image',
            field=models.ImageField(default='', upload_to='imgs/%y'),
        ),
    ]
